### ISSUE TITLE
Plans to upgrade to Jersey 2?

### ISSUE THREAD

**Issue by derekcicerone** [silb/shiro-jersey#6]
Love this library - we were wondering if you have plans to upgrade it for Jersey 2 in DropWizard 0.8.0.

**Comment by segfly** [comment]
**+1** I definitely prefer your library over [dw-shiro-bundle](https://github.com/Multifarious/dw-shiro-bundle) because yours supports declarative authorizations. Unfortunately, we need Dropwizard 0.8 due to other dependencies and currently [dw-shiro-bundle](https://github.com/Multifarious/dw-shiro-bundle) works with 0.8.

Any idea on release date?

**Comment by silb** [comment]
I don't have a release date for you.

But the Dropwizard 0.8 / Jersey 2 work is pretty much done. What remains is some documentation and merging the changes back into master. And I'm also waiting for Dropwizard 0.8 to be released.

If you need them **now** you can build your own binaries from the branches I linked to in my previous comment.

**Comment by segfly** [comment]
@silb Great! I wasn't sure what state those branches were in. Are both projects the same in this regard? Thanks.

**Comment by silb** [comment]
Yes, the branches in both projects are in a working state. All the tests passes.

**Comment by silb** [comment]
New versions are available in Maven Central:

* Version 0.2.0 of `org.secnod.shiro:shiro-jersey` supporting Jersey 2
* Version 0.2.0 of `org.secnod.dropwizard:dropwizard-shiro` supporting Dropwizard 0.8.0
